package utils

import (
	"errors"
	"net/http"

	"github.com/elastic/go-elasticsearch/v8"
)

// Connect takes a config generated by utils.Configure and returns an elasticsearch client and error
func Connect() (*elasticsearch.Client, error) {
	cfg := Configure()
	es, err := elasticsearch.NewClient(cfg)
	if err != nil {
		return nil, err
	}
	// Run Info to actually check connection
	r, err := es.Info()
	if err != nil {
		return nil, err
	}
	if r.StatusCode == http.StatusOK {
		// Good status, return es client
		return es, nil
	}
	if r.StatusCode == http.StatusUnauthorized {
		return nil, errors.New("unauthorized")
	}
	// Status was not unauthorized or OK
	return nil, errors.New("undefined error")
}
